### PR TITLE
fix log positional parameters

### LINKED ISSUE #89: [BUG] Fix operate incomplete log
missing log err in operator autoscaler

image

### PR DESCRIPTION
**Pull request by kevincai**
* fixes #89

### CODE REVIEW

File: pkg/sub_controller/cn/cn_controller.go [hunk 1]
```diff
@@ -300,7 +300,7 @@ func (cc *CnController) deployAutoScaler(ctx context.Context, policy srapi.AutoS
 	params := cc.buildCnAutoscalerParams(policy, target, src)
 	autoScaler := rutils.BuildHorizontalPodAutoscaler(params)
 	if err := k8sutils.PatchOrCreate(ctx, cc.k8sclient, autoScaler); err != nil {
-		klog.Errorf("cnController deployAutoscaler failed, namespace=%s,name=%s,version=%s,error=%s", autoScaler.GetNamespace(), autoScaler.GetNamespace(), policy.Version)
+		klog.Errorf("cnController deployAutoscaler failed, namespace=%s,name=%s,version=%s,error=%s", autoScaler.GetNamespace(), autoScaler.GetName(), policy.Version, err.Error())
```
Comment (intelligentfu) [inline pkg/sub_controller/cn/cn_controller.go:303]: the format should error=%s\n

Comment (shileifu) [inline pkg/sub_controller/cn/cn_controller.go:303]: the right format should error=%s\n

Comment (kevincai) [reply pkg/sub_controller/cn/cn_controller.go:303]:
```
func Errorf(format [string](https://pkg.go.dev/builtin#string), args ...interface{})
Errorf logs to the ERROR, WARNING, and INFO logs. Arguments are handled in the manner of fmt.Printf; a newline is appended if missing.
```

looks like it's fine without `\n`
